
---
- name: Provision New Server
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules
    - servicenow.itsm
  tasks:

    - name: return next available IP address from {{ parent_network }} in NIOS
      set_fact:
        new_vm_ip_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', parent_network,
                            provider={'host': nios.host, 'username': nios.username, 'password': nios.password}) }}"

    - name: set facts about the new vm
      ansible.builtin.set_fact:
        instance:
          name: "{{ vm.host_name}}-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=6') }}"
          id: "{{ vm.id }}"
   

    - name: configure an ipv4 host record for {{ instance.name }} {{ new_vm_ip_address[0] }} in NIOS
      nios_host_record:
        name: "{{ instance.name }}.lab.local"
        ipv4:
          - address: "{{ new_vm_ip_address[0] }}"
        state: present
        provider: "{{ nios }} "

    - name: register {{ instance.name }} vm in service-now cmdb
      servicenow.itsm.configuration_item:
        name: "{{  instance.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ new_vm_ip_address[0] }}"
        other:
          vm_inst_id: "{{ vm.id }}"
          os: "{{ vm.os }}"
        instance:
          host: "{{snow_host }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"