
---
- name: Provision New Server
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules
    - servicenow.itsm
  
  tasks:

    - name: return next available IP address
      set_fact:
        new_vm_ip_address: "{{ lookup('infoblox.nios_modules.nios_next_ip', parent_network,
                            provider={'host': nios.host, 'username': nios.username, 'password': nios.password}) }}"

    - debug:
        msg: "The new VM will have {{ new_vm_ip_address[0] }} asssigned."

    - name: set facts about the new vm
      ansible.builtin.set_fact:
        instance:
          name: "{{ vm.name }}"
          id: "{{ vm.id }}"
   

    - name: configure an ipv4 host record
      nios_host_record:
        name: "{{ instance.name }}.lab.local"
        ipv4:
          - address: "{{ new_vm_ip_address[0] }}"
        state: present
        provider: "{{ nios }} "

    - name: register new vm in snow cmdb
      servicenow.itsm.configuration_item:
        name: "{{ instance.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ new_vm_ip_address[0] }}"
        other:
          vm_inst_id: "{{ instance.id }}" 